import type { RouteRecordRaw } from 'vue-router';
import ConsoleMobileShell from '../layouts/ConsoleMobileShell.vue';
import { communityRouteGuard, payoutPolicyGuard } from './guards';

export const consoleMobileRoutes: RouteRecordRaw = {
  path: '/console',
  component: ConsoleMobileShell,
  meta: {
    requiresAuth: true,
    requiresOrganizer: true,
    layout: 'console-mobile',
    stackKey: 'mobile',
    devPageName: 'Console モバイルシェル',
    navTransition: 'none',
  },
  children: [
    {
      path: '',
      name: 'ConsoleMobileHome',
      component: () => import('../views/console/mobile/ConsoleHomeMobile.vue'),
      meta: {
        title: 'コミュニティ管理',
        stackKey: 'mobile',
        keepAlive: true,
        devPageName: 'Console-ホーム',
        hideShellHeader: true,
        flushContent: true,
        navTransition: 'none',
      },
    },
    {
      path: 'communities/:communityId/events',
      name: 'ConsoleMobileCommunityEvents',
      component: () => import('../views/console/mobile/ConsoleCommunityEventsMobile.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: 'コミュニティイベント',
        stackKey: 'mobile',
        keepAlive: true,
        devPageName: 'Console-コミュニティイベント',
        hideShellHeader: true,
        flushContent: true,
      },
    },
    {
      path: 'classes',
      name: 'ConsoleMobileClasses',
      component: () => import('../views/console/mobile/ConsoleClassesListMobile.vue'),
      meta: {
        title: '教室管理',
        hideShellHeader: true,
        hideTabbar: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        keepAlive: true,
        devPageName: 'Console-教室一覧',
      },
    },
    {
      path: 'classes/new',
      name: 'ConsoleMobileClassForm',
      component: () => import('../views/console/mobile/ConsoleClassFormMobile.vue'),
      meta: {
        title: '教室を作成',
        hideShellHeader: true,
        hideTabbar: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        devPageName: 'Console-教室フォーム',
      },
    },
    {
      path: 'classes/:classId/lessons',
      name: 'ConsoleMobileLessons',
      component: () => import('../views/console/mobile/ConsoleLessonsMobile.vue'),
      meta: {
        title: 'レッスン管理',
        hideShellHeader: true,
        hideTabbar: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        devPageName: 'Console-レッスン管理',
      },
      props: true,
    },
    {
      path: 'lessons/:lessonId/registrations',
      name: 'ConsoleMobileLessonRegistrations',
      component: () => import('../views/console/mobile/ConsoleLessonRegistrationsMobile.vue'),
      meta: {
        title: '申込一覧',
        hideShellHeader: true,
        hideTabbar: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        devPageName: 'Console-レッスン申込',
      },
      props: true,
    },
    {
      path: 'communities/new',
      name: 'ConsoleMobileCommunityCreate',
      component: () => import('../views/console/mobile/ConsoleCommunitySettingsMobile.vue'),
      meta: {
        title: 'コミュニティ作成',
        hideTabbar: true,
        hideShellHeader: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        devPageName: 'Console-コミュニティ作成',
      },
    },
    {
      path: 'communities/:communityId/events/paste',
      name: 'ConsoleMobileEventPaste',
      component: () => import('../views/console/mobile/ConsoleEventPasteMobile.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: '下書きを貼り付ける',
        hideTabbar: true,
        hideShellHeader: true,
        flushContent: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        devPageName: 'Console-下書き貼り付け',
      },
    },
    {
      path: 'communities/:communityId/events/create',
      name: 'ConsoleMobileEventCreate',
      component: () => import('../views/console/mobile/ConsoleEventAssistantMobile.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: 'イベント作成',
        hideTabbar: true,
        hideShellHeader: true,
        fixedPage: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        devPageName: 'Console-イベントアシスタント',
      },
    },
    {
      path: 'communities/:communityId/event-assistant/dashboard',
      name: 'ConsoleMobileAssistantDashboard',
      component: () => import('../views/console/mobile/ConsoleEventAssistantDashboard.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: 'アシスタントダッシュボード',
        stackKey: 'mobile',
        hideTabbar: true,
        hideShellHeader: true,
        flushContent: true,
        devPageName: 'Console-アシスタントダッシュボード',
      },
    },
    {
      path: 'communities/:communityId/event-assistant/logs',
      name: 'ConsoleMobileAssistantLogs',
      component: () => import('../views/console/mobile/ConsoleEventAssistantLogsMobile.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: 'アシスタント履歴',
        stackKey: 'mobile',
        hideTabbar: true,
        hideShellHeader: true,
        flushContent: true,
        devPageName: 'Console-アシスタント履歴',
      },
    },
    {
      path: 'communities/:communityId/events/form',
      name: 'ConsoleMobileEventForm',
      component: () => import('../views/console/EventForm.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: 'イベント作成',
        hideTabbar: true,
        hideShellHeader: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        devPageName: 'Console-イベントフォーム',
      },
    },
    {
      path: 'communities/:communityId/events/more-settings',
      name: 'ConsoleMobileEventMoreSettings',
      component: () => import('../views/console/EventForm.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: '追加設定',
        hideTabbar: true,
        hideShellHeader: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        devPageName: 'Console-追加設定',
      },
    },
    {
      path: 'communities/:communityId/events/note-editor',
      name: 'ConsoleMobileEventNoteEditor',
      component: () => import('../views/console/mobile/ConsoleEventNoteEditorMobile.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: 'イベント詳細編集',
        hideTabbar: true,
        hideShellHeader: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        devPageName: 'Console-イベント詳細編集',
      },
    },
    {
      path: 'communities/:communityId/settings',
      name: 'ConsoleMobileCommunitySettings',
      component: () => import('../views/console/mobile/ConsoleCommunitySettingsMobile.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: 'コミュニティ設定',
        stackKey: 'mobile',
        hideTabbar: true,
        hideShellHeader: true,
        devPageName: 'Console-コミュニティ設定',
        flushContent: true,
      },
    },
    {
      path: 'communities/:communityId/portal',
      name: 'ConsoleMobileCommunityPortal',
      component: () => import('../views/console/mobile/ConsoleCommunityPortalMobile.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: 'ポータル設定',
        hideTabbar: true,
        hideShellHeader: true,
        devPageName: 'Console-ポータルテンプレート',
        flushContent: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
      },
    },
    {
      path: 'events/:eventId/manage',
      name: 'ConsoleMobileEventManage',
      component: () => import('../views/console/mobile/ConsoleEventManageMobile.vue'),
      meta: {
        title: 'イベント管理',
        stackKey: 'mobile',
        devPageName: 'Console-イベント管理',
        hideShellHeader: true,
        hideTabbar: true,
        flushContent: true,
      },
    },
    {
      path: 'events/:eventId/publish-success',
      name: 'ConsoleMobileEventPublishSuccess',
      component: () => import('../views/console/mobile/ConsoleEventPublishSuccessMobile.vue'),
      meta: {
        title: '公開完了',
        hideTabbar: true,
        hideShellHeader: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        devPageName: 'Console-公開完了',
      },
    },
    {
      path: 'settings/payout',
      name: 'ConsoleMobilePayout',
      component: () => import('../views/console/mobile/PayoutSettingsMobile.vue'),
      beforeEnter: payoutPolicyGuard,
      meta: {
        title: 'コミュニティ財務',
        devPageName: 'Console-受け取り設定',
        flushContent: true,
        hideShellHeader: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        hideTabbar: true,
      },
    },
    {
      path: 'communities/:communityId/payments',
      name: 'ConsoleMobilePayments',
      component: () => import('../views/console/mobile/ConsolePaymentsMobile.vue'),
      beforeEnter: communityRouteGuard,
      meta: {
        title: '決済履歴',
        devPageName: 'Console-決済履歴',
        hideTabbar: true,
        hideShellHeader: true,
        flushContent: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
      },
    },
    {
      path: 'subscription',
      name: 'ConsoleMobileSubscription',
      beforeEnter: (_to, _from, next) => next({ name: 'ConsoleMobileSubscriptionStandalone' }),
      component: () => import('../views/console/mobile/SubscriptionMobile.vue'),
      meta: {
        title: 'サブスクリプション',
        devPageName: 'Console-サブスク管理',
        hideShellHeader: true,
        hideTabbar: true,
        flushContent: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
      },
    },
    {
      path: 'tickets/scanner',
      name: 'ConsoleTicketScanner',
      component: () => import('../views/console/mobile/ConsoleTicketScannerMobile.vue'),
      meta: {
        title: 'チケットスキャン',
        hideTabbar: true,
        hideShellHeader: true,
        layout: 'console-mobile',
        stackKey: 'mobile',
        flushContent: true,
        devPageName: 'Console-チケットスキャン',
      },
    },
  ],
};

export const consoleMobileStandaloneRoutes: RouteRecordRaw[] = [
  {
    path: '/console-subscription',
    name: 'ConsoleMobileSubscriptionStandalone',
    component: () => import('../views/console/mobile/SubscriptionMobile.vue'),
    meta: {
      devPageName: 'Console-サブスク管理（独立）',
      hideTabbar: true,
      hideShellHeader: true,
      layout: 'console-mobile',
      stackKey: 'mobile',
      flushContent: true,
    },
  },
];
