import { NotificationTemplate, NotificationType } from './notification.types';

export const NOTIFICATION_TEMPLATES: Record<NotificationType, NotificationTemplate> = {
  'user.email.verify': {
    label: 'T01 メール認証',
    description: '参加者のメールアドレス確認',
    defaultEnabled: true,
    role: 'user',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '【要対応】メールアドレス確認（{{service_name}}）',
        body: [
          '確認コード：{{verify_code}}',
          '有効期限：{{expires_at}}',
          '',
          '{{user_name}} 様',
          '',
          '{{service_name}} のご利用ありがとうございます。',
          '',
          'アプリのメール通知設定画面に入力してください。',
          '',
          'このメールに心当たりがない場合は、破棄してください。',
          '',
          '※本メールは自動送信です。返信いただいても対応できません。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート',
          '{{#support_url}}お問い合わせ：{{support_url}}{{/support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '請驗證你的電子郵件（{{service_name}}）',
        body: [
          '驗證碼：{{verify_code}}',
          '有效期限：{{expires_at}}',
          '',
          '{{user_name}} 您好',
          '',
          '感謝使用 {{service_name}}。',
          '',
          '請在 App 的郵件通知設定畫面輸入驗證碼。',
          '',
          '若非您本人操作，請忽略並刪除此信。',
          '',
          '※此信為系統自動寄送，請勿直接回覆。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服',
          '{{#support_url}}聯絡我們：{{support_url}}{{/support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.registration.created': {
    label: 'T02 申込受付',
    description: '申込/申請の受付完了',
    defaultEnabled: false,
    role: 'user',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '申込を受け付けました｜{{event_name}}（申込番号 {{order_id}}）',
        body: [
          '{{user_name}} 様',
          '',
          '{{service_name}} のご利用ありがとうございます。',
          '',
          '{{event_name}} のお申し込みを受け付けました。',
          '',
          '■ お申し込み内容',
          '・申込番号：{{order_id}}',
          '・イベント名：{{event_name}}',
          '・日時：{{event_datetime}}',
          '・場所：{{event_location}}',
          '・ステータス：{{application_status}}',
          '',
          '■ 次のステップ',
          '{{next_step_text}}',
          '',
          '申込詳細：{{order_detail_url}}',
          '{{#policy_url}}キャンセル／返金ポリシー：{{policy_url}}{{/policy_url}}',
          '',
          '※本メールは自動送信です。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '已收到你的報名｜{{event_name}}（申請編號 {{order_id}}）',
        body: [
          '{{user_name}} 您好',
          '',
          '感謝使用 {{service_name}}。',
          '',
          '我們已收到您對「{{event_name}}」的報名/申請。',
          '',
          '■ 申請內容',
          '・申請/訂單編號：{{order_id}}',
          '・活動名稱：{{event_name}}',
          '・時間：{{event_datetime}}',
          '・地點：{{event_location}}',
          '・狀態：{{application_status}}',
          '',
          '■ 下一步',
          '{{next_step_text}}',
          '',
          '申請詳情：{{order_detail_url}}',
          '{{#policy_url}}取消/退款規則：{{policy_url}}{{/policy_url}}',
          '',
          '※此信為系統自動寄送。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.registration.approved': {
    label: 'T03A 申込承認',
    description: '審査承認（支払い案内含む）',
    defaultEnabled: false,
    role: 'user',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '申込が承認されました｜{{event_name}}（{{order_id}}）',
        body: [
          '{{user_name}} 様',
          '',
          '{{event_name}} のお申し込みが承認されました。',
          '',
          '{{next_step_text}}',
          '',
          '{{#payment_url}}■ お支払い情報',
          '・申込番号：{{order_id}}',
          '・金額：{{amount}}',
          '{{#payment_due_at}}・支払期限：{{payment_due_at}}{{/payment_due_at}}',
          'お支払いはこちら：{{payment_url}}',
          '{{/payment_url}}',
          '',
          '詳細：{{order_detail_url}}',
          '',
          '※本メールは自動送信です。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '申請已核准｜{{event_name}}（{{order_id}}）',
        body: [
          '{{user_name}} 您好',
          '',
          '您對「{{event_name}}」的申請已通過審核。',
          '',
          '{{next_step_text}}',
          '',
          '{{#payment_url}}■ 付款資訊',
          '・訂單編號：{{order_id}}',
          '・金額：{{amount}}',
          '{{#payment_due_at}}・付款期限：{{payment_due_at}}{{/payment_due_at}}',
          '付款連結：{{payment_url}}',
          '{{/payment_url}}',
          '',
          '詳情：{{order_detail_url}}',
          '',
          '※此信為系統自動寄送。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.registration.rejected': {
    label: 'T03B 申込却下',
    description: '審査否認',
    defaultEnabled: false,
    role: 'user',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '申込が拒否されました｜{{event_name}}（{{order_id}}）',
        body: [
          '{{user_name}} 様',
          '',
          '{{event_name}} のお申し込みは、残念ながら承認されませんでした。',
          '',
          '■ お申し込み情報',
          '・申込番号：{{order_id}}',
          '・イベント名：{{event_name}}',
          '{{#reject_reason}}',
          '■ 理由',
          '{{reject_reason}}',
          '{{/reject_reason}}',
          '',
          '詳細：{{order_detail_url}}',
          '',
          '※本メールは自動送信です。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '申請未通過｜{{event_name}}（{{order_id}}）',
        body: [
          '{{user_name}} 您好',
          '',
          '很抱歉，您對「{{event_name}}」的申請未通過。',
          '',
          '■ 申請資訊',
          '・訂單/申請編號：{{order_id}}',
          '・活動名稱：{{event_name}}',
          '{{#reject_reason}}',
          '■ 原因',
          '{{reject_reason}}',
          '{{/reject_reason}}',
          '',
          '詳情：{{order_detail_url}}',
          '',
          '※此信為系統自動寄送。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.payment.succeeded': {
    label: 'T04 付款成功',
    description: '支払い成功',
    defaultEnabled: false,
    role: 'user',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: 'お支払い完了｜{{event_name}}（注文 {{order_id}}）',
        body: [
          '{{user_name}} 様',
          '',
          'お支払いが正常に完了しました。',
          '',
          '■ お支払い情報',
          '・注文番号：{{order_id}}',
          '・金額：{{amount}}',
          '・支払日時：{{paid_at}}',
          '{{#payment_method}}・支払方法：{{payment_method}}{{/payment_method}}',
          '',
          '■ イベント情報',
          '・イベント名：{{event_name}}',
          '・日時：{{event_datetime}}',
          '・場所：{{event_location}}',
          '',
          '注文詳細：{{order_detail_url}}',
          '{{#policy_url}}キャンセル／返金ポリシー：{{policy_url}}{{/policy_url}}',
          '',
          '※本メールは自動送信です。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '付款成功｜{{event_name}}（訂單 {{order_id}}）',
        body: [
          '{{user_name}} 您好',
          '',
          '付款已成功完成，請確認以下內容。',
          '',
          '■ 付款資訊',
          '・訂單編號：{{order_id}}',
          '・金額：{{amount}}',
          '・付款時間：{{paid_at}}',
          '{{#payment_method}}・付款方式：{{payment_method}}{{/payment_method}}',
          '',
          '■ 活動資訊',
          '・活動名稱：{{event_name}}',
          '・時間：{{event_datetime}}',
          '・地點：{{event_location}}',
          '',
          '訂單明細：{{order_detail_url}}',
          '{{#policy_url}}取消/退款規則：{{policy_url}}{{/policy_url}}',
          '',
          '※此信為系統自動寄送。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.payment.failed': {
    label: 'T05 付款失敗',
    description: '支払い失敗',
    defaultEnabled: false,
    role: 'user',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: 'お支払い未完了｜再決済のお願い：{{event_name}}（{{order_id}}）',
        body: [
          '{{user_name}} 様',
          '',
          'お支払いが完了していません。',
          '',
          '参加を確定するため、以下から再度お支払い手続きをお願いします。',
          '',
          '■ 注文情報',
          '・注文番号：{{order_id}}',
          '・金額：{{amount}}',
          '{{#failure_reason}}',
          '■ 補足',
          '{{failure_reason}}',
          '{{/failure_reason}}',
          '',
          '再決済はこちら：{{payment_url}}',
          '{{#payment_due_at}}支払期限：{{payment_due_at}}{{/payment_due_at}}',
          '',
          '※本メールは自動送信です。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '付款未完成｜請重新付款：{{event_name}}（{{order_id}}）',
        body: [
          '{{user_name}} 您好',
          '',
          '您的付款尚未完成。',
          '',
          '為確保參加資格，請由下方連結重新付款。',
          '',
          '■ 訂單資訊',
          '・訂單編號：{{order_id}}',
          '・金額：{{amount}}',
          '{{#failure_reason}}',
          '■ 補充說明',
          '{{failure_reason}}',
          '{{/failure_reason}}',
          '',
          '重新付款：{{payment_url}}',
          '{{#payment_due_at}}付款期限：{{payment_due_at}}{{/payment_due_at}}',
          '',
          '※此信為系統自動寄送。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.payment.expired': {
    label: 'T06 付款逾期取消',
    description: '支払い期限切れによる自動取消',
    defaultEnabled: false,
    role: 'user',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '支払期限超過｜申込は自動キャンセルされました：{{event_name}}（{{order_id}}）',
        body: [
          '{{user_name}} 様',
          '',
          '支払期限までにお支払いが確認できなかったため、お申し込みは自動キャンセルとなりました。',
          '',
          '■ 対象申込',
          '・申込番号：{{order_id}}',
          '・イベント名：{{event_name}}',
          '{{#payment_due_at}}・支払期限：{{payment_due_at}}{{/payment_due_at}}',
          '{{#cancelled_at}}・キャンセル日時：{{cancelled_at}}{{/cancelled_at}}',
          '',
          '再申込：{{event_page_url}}',
          '',
          '※本メールは自動送信です。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '付款逾期｜申請已自動取消：{{event_name}}（{{order_id}}）',
        body: [
          '{{user_name}} 您好',
          '',
          '由於在付款期限前未確認到付款，您的申請已被系統自動取消。',
          '',
          '■ 對應申請',
          '・訂單/申請編號：{{order_id}}',
          '・活動名稱：{{event_name}}',
          '{{#payment_due_at}}・付款期限：{{payment_due_at}}{{/payment_due_at}}',
          '{{#cancelled_at}}・取消時間：{{cancelled_at}}{{/cancelled_at}}',
          '',
          '重新報名：{{event_page_url}}',
          '',
          '※此信為系統自動寄送。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.event.cancelled': {
    label: 'T07 活動取消',
    description: 'イベント中止の案内',
    defaultEnabled: false,
    role: 'user',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '【重要】イベント中止のお知らせ｜{{event_name}}',
        body: [
          '{{user_name}} 様',
          '',
          '重要なお知らせです。',
          '',
          '{{event_name}} は中止となりました。',
          '',
          '■ 対象イベント',
          '・イベント名：{{event_name}}',
          '・日時：{{event_datetime}}',
          '・場所：{{event_location}}',
          '',
          '{{#refund_policy_text}}■ 返金について',
          '{{refund_policy_text}}',
          '{{#refund_eta}}返金反映目安：{{refund_eta}}{{/refund_eta}}',
          '{{/refund_policy_text}}',
          '',
          '注文／申込確認：{{order_detail_url}}',
          '',
          '※本メールは自動送信です。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '【重要】活動已取消｜{{event_name}}',
        body: [
          '{{user_name}} 您好',
          '',
          '重要通知：',
          '',
          '「{{event_name}}」已取消。',
          '',
          '■ 活動資訊',
          '・活動名稱：{{event_name}}',
          '・時間：{{event_datetime}}',
          '・地點：{{event_location}}',
          '',
          '{{#refund_policy_text}}■ 退款說明',
          '{{refund_policy_text}}',
          '{{#refund_eta}}退款入帳時間估計：{{refund_eta}}{{/refund_eta}}',
          '{{/refund_policy_text}}',
          '',
          '查看訂單/申請：{{order_detail_url}}',
          '',
          '※此信為系統自動寄送。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.event.changed': {
    label: 'T08 活動重大變更',
    description: 'イベント重要情報の変更',
    defaultEnabled: false,
    role: 'user',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '【重要】イベント情報が変更されました｜{{event_name}}',
        body: [
          '{{user_name}} 様',
          '',
          '{{event_name}} の情報が更新されました。',
          'ご参加前に必ず最新情報をご確認ください。',
          '',
          '■ 変更内容（要点）',
          '{{change_summary}}',
          '',
          '■ 変更前',
          '{{before_block}}',
          '',
          '■ 変更後',
          '{{after_block}}',
          '',
          '最新情報：{{event_page_url}}',
          '{{#policy_url}}キャンセル／返金ポリシー：{{policy_url}}{{/policy_url}}',
          '',
          '※本メールは自動送信です。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '【重要】活動資訊已變更｜{{event_name}}',
        body: [
          '{{user_name}} 您好',
          '',
          '「{{event_name}}」活動資訊已更新。',
          '請在參加前務必確認最新內容。',
          '',
          '■ 變更重點',
          '{{change_summary}}',
          '',
          '■ 變更前',
          '{{before_block}}',
          '',
          '■ 變更後',
          '{{after_block}}',
          '',
          '最新資訊：{{event_page_url}}',
          '{{#policy_url}}取消/退款規則：{{policy_url}}{{/policy_url}}',
          '',
          '※此信為系統自動寄送。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.refund.success': {
    label: 'T09A 退款成功',
    description: '返金完了',
    defaultEnabled: false,
    role: 'user',
    category: 'transactional',
    line: {
      ja: {
        title: '返金が完了しました',
        body: '{{eventTitle}} の返金が完了しました。返金額: {{refundAmount}}',
      },
    },
    email: {
      ja: {
        subject: '返金が完了しました｜{{event_name}}（注文 {{order_id}}）',
        body: [
          '{{user_name}} 様',
          '',
          '返金が完了しました。',
          '',
          '■ 返金情報',
          '・注文番号：{{order_id}}',
          '・返金金額：{{refund_amount}}',
          '・返金日時：{{refunded_at}}',
          '{{#settlement_eta}}・入金反映の目安：{{settlement_eta}}{{/settlement_eta}}',
          '',
          '明細：{{order_detail_url}}',
          '',
          '※本メールは自動送信です。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '退款已完成｜{{event_name}}（訂單 {{order_id}}）',
        body: [
          '{{user_name}} 您好',
          '',
          '退款已完成，請確認以下內容。',
          '',
          '■ 退款資訊',
          '・訂單編號：{{order_id}}',
          '・退款金額：{{refund_amount}}',
          '・退款時間：{{refunded_at}}',
          '{{#settlement_eta}}・入帳時間估計：{{settlement_eta}}{{/settlement_eta}}',
          '',
          '明細：{{order_detail_url}}',
          '',
          '※此信為系統自動寄送。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.refund.failed': {
    label: 'T09B 退款失敗',
    description: '返金失敗/要対応',
    defaultEnabled: false,
    role: 'user',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '返金が未完了です｜ご対応のお願い（注文 {{order_id}}）',
        body: [
          '{{user_name}} 様',
          '',
          '返金手続きが完了していません。',
          'お手数ですが、以下をご確認のうえご対応ください。',
          '',
          '■ 対象注文',
          '・注文番号：{{order_id}}',
          '・イベント名：{{event_name}}',
          '・現在の状況：{{refund_status}}',
          '',
          '■ 必要な対応',
          '{{required_action_text}}',
          '手続き：{{action_url}}',
          '{{#optional_deadline}}期限：{{optional_deadline}}{{/optional_deadline}}',
          '',
          '※本メールは自動送信です。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '退款未完成｜請完成必要處理（訂單 {{order_id}}）',
        body: [
          '{{user_name}} 您好',
          '',
          '退款程序尚未完成。',
          '請確認以下資訊並完成必要操作。',
          '',
          '■ 對應訂單',
          '・訂單編號：{{order_id}}',
          '・活動名稱：{{event_name}}',
          '・目前狀態：{{refund_status}}',
          '',
          '■ 需要您處理的事項',
          '{{required_action_text}}',
          '前往處理：{{action_url}}',
          '{{#optional_deadline}}期限：{{optional_deadline}}{{/optional_deadline}}',
          '',
          '※此信為系統自動寄送。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.email.verify': {
    label: 'H01 主催者メール認証',
    description: '主催者のメールアドレス確認',
    defaultEnabled: true,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '【要対応】主催者メールアドレス確認（{{service_name}}）',
        body: [
          '確認コード：{{verify_code}}',
          '有効期限：{{expires_at}}',
          '',
          '{{organizer_name}} 様',
          '',
          '{{service_name}} のご利用ありがとうございます。',
          '',
          'アプリのメール通知設定画面に入力してください。',
          '',
          'このメールに心当たりがない場合は、破棄してください。',
          '',
          '※本メールは自動送信です。返信いただいても対応できません。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート',
          '{{#support_url}}お問い合わせ：{{support_url}}{{/support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '【需處理】主辦者 Email 驗證（{{service_name}}）',
        body: [
          '驗證碼：{{verify_code}}',
          '有效期限：{{expires_at}}',
          '',
          '{{organizer_name}} 您好',
          '',
          '感謝使用 {{service_name}}。',
          '',
          '請在 App 的郵件通知設定畫面輸入驗證碼。',
          '',
          '若非您本人操作，請忽略並刪除此信。',
          '',
          '※此信為系統自動寄送，請勿直接回覆。',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.event.submitted': {
    label: 'H02 イベント送信',
    description: 'イベント送信/作成完了',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: 'イベントを作成しました｜{{event_name}}',
        body: [
          '{{organizer_name}} 様',
          '',
          'イベントを作成しました。以下から管理できます。',
          '',
          '■ イベント情報',
          '・イベント名：{{event_name}}',
          '・日時：{{event_datetime}}',
          '・場所：{{event_location}}',
          '',
          '{{#event_manage_url}}管理画面：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '已建立活動｜{{event_name}}',
        body: [
          '{{organizer_name}} 您好',
          '',
          '活動已建立完成，可由下方連結進入管理。',
          '',
          '■ 活動資訊',
          '・活動名稱：{{event_name}}',
          '・時間：{{event_datetime}}',
          '・地點：{{event_location}}',
          '',
          '{{#event_manage_url}}管理入口：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.event.review.approved': {
    label: 'H03A 審査通過',
    description: '審査通過/公開',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '審査通過｜イベントが公開されました：{{event_name}}',
        body: [
          '{{organizer_name}} 様',
          '',
          '{{event_name}} の審査が通過し、イベントが公開されました。',
          '',
          '{{#event_page_url}}公開ページ：{{event_page_url}}{{/event_page_url}}',
          '{{#event_manage_url}}管理画面：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '審核通過｜活動已上架：{{event_name}}',
        body: [
          '{{organizer_name}} 您好',
          '',
          '「{{event_name}}」已通過審核並完成上架。',
          '',
          '{{#event_page_url}}活動頁：{{event_page_url}}{{/event_page_url}}',
          '{{#event_manage_url}}管理頁：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.event.review.rejected': {
    label: 'H03B 審査要修正',
    description: '審査却下/要修正',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '審査要修正｜イベント内容をご確認ください：{{event_name}}',
        body: [
          '{{organizer_name}} 様',
          '',
          '{{event_name}} は審査の結果、修正が必要です。',
          '',
          '{{#review_reason}}■ 指摘内容',
          '{{review_reason}}',
          '{{/review_reason}}',
          '',
          '{{#event_manage_url}}修正・再申請：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '需要修改｜請確認活動內容：{{event_name}}',
        body: [
          '{{organizer_name}} 您好',
          '',
          '「{{event_name}}」審核結果需要修改後再送審。',
          '',
          '{{#review_reason}}■ 指出事項',
          '{{review_reason}}',
          '{{/review_reason}}',
          '',
          '{{#event_manage_url}}前往修改/重新送審：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.registration.pending': {
    label: 'H04 新規申込（審査）',
    description: '新しい申込の審査依頼',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '【要対応】新しい申込があります｜{{event_name}}',
        body: [
          '{{organizer_name}} 様',
          '',
          '{{event_name}} に新しい申込が届きました。審査/承認が必要です。',
          '',
          '■ 申込情報',
          '・申込番号：{{order_id}}',
          '{{#participant_display_name}}・申込者：{{participant_display_name}}{{/participant_display_name}}',
          '{{#quantity}}・数量：{{quantity}}{{/quantity}}',
          '{{#applied_at}}・申込日時：{{applied_at}}{{/applied_at}}',
          '',
          '{{#order_detail_url}}承認／拒否：{{order_detail_url}}{{/order_detail_url}}',
          '',
          '※対応が遅れると参加者が離脱する可能性があります。',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '【需處理】有新的報名申請｜{{event_name}}',
        body: [
          '{{organizer_name}} 您好',
          '',
          '「{{event_name}}」收到新的報名申請，需要您審核/承認。',
          '',
          '■ 申請資訊',
          '・申請編號：{{order_id}}',
          '{{#participant_display_name}}・申請者：{{participant_display_name}}{{/participant_display_name}}',
          '{{#quantity}}・數量：{{quantity}}{{/quantity}}',
          '{{#applied_at}}・申請時間：{{applied_at}}{{/applied_at}}',
          '',
          '{{#order_detail_url}}前往承認/拒絕：{{order_detail_url}}{{/order_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.payment.expired': {
    label: 'H07 支払期限切れ',
    description: '支払期限切れによる自動キャンセル',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '支払期限切れ｜申込は自動キャンセルされました：{{event_name}}（{{order_id}}）',
        body: [
          '{{organizer_name}} 様',
          '',
          '支払期限までに支払いが確認できなかったため、申込は自動キャンセルとなりました。',
          '',
          '■ 対象',
          '・イベント名：{{event_name}}',
          '・申込番号：{{order_id}}',
          '{{#participant_display_name}}・申込者：{{participant_display_name}}{{/participant_display_name}}',
          '{{#payment_due_at}}・支払期限：{{payment_due_at}}{{/payment_due_at}}',
          '{{#cancelled_at}}・キャンセル日時：{{cancelled_at}}{{/cancelled_at}}',
          '',
          '{{#event_manage_url}}管理画面：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '付款逾期｜申請已自動取消：{{event_name}}（{{order_id}}）',
        body: [
          '{{organizer_name}} 您好',
          '',
          '由於參加者未在付款期限內完成付款，系統已自動取消該申請（名額將釋出）。',
          '',
          '■ 對應資訊',
          '・活動：{{event_name}}',
          '・申請編號：{{order_id}}',
          '{{#participant_display_name}}・申請者：{{participant_display_name}}{{/participant_display_name}}',
          '{{#payment_due_at}}・付款期限：{{payment_due_at}}{{/payment_due_at}}',
          '{{#cancelled_at}}・取消時間：{{cancelled_at}}{{/cancelled_at}}',
          '',
          '{{#event_manage_url}}活動管理：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.event.system_cancelled': {
    label: 'H08 システム停止',
    description: 'システムによるイベント停止',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '【重要】イベントが停止されました｜{{event_name}}',
        body: [
          '{{organizer_name}} 様',
          '',
          '{{event_name}} はシステムにより停止（非公開）されました。',
          '',
          '{{#system_action_reason}}■ 理由',
          '{{system_action_reason}}',
          '{{/system_action_reason}}',
          '',
          '{{#event_manage_url}}状況確認：{{event_manage_url}}{{/event_manage_url}}',
          '{{#support_url}}ご不明点：{{support_url}}{{/support_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '【重要】活動已被系統停止/下架｜{{event_name}}',
        body: [
          '{{organizer_name}} 您好',
          '',
          '「{{event_name}}」已被系統停止（轉為非公開）。',
          '',
          '{{#system_action_reason}}■ 原因',
          '{{system_action_reason}}',
          '{{/system_action_reason}}',
          '',
          '{{#event_manage_url}}前往確認：{{event_manage_url}}{{/event_manage_url}}',
          '{{#support_url}}客服：{{support_url}}{{/support_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.event.reminder': {
    label: 'H09 開催前リマインド',
    description: '開催48時間前リマインド',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '開催まもなく｜準備のご案内：{{event_name}}',
        body: [
          '{{organizer_name}} 様',
          '',
          '{{event_name}} の開催が近づいています。運営準備をご確認ください。',
          '',
          '■ 開催情報',
          '・日時：{{event_datetime}}',
          '・場所：{{event_location}}',
          '{{#participant_list_url}}・参加者一覧：{{participant_list_url}}{{/participant_list_url}}',
          '',
          '{{#event_manage_url}}イベント管理：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '活動即將開始｜請確認準備事項：{{event_name}}',
        body: [
          '{{organizer_name}} 您好',
          '',
          '「{{event_name}}」即將開始，請確認活動運營準備。',
          '',
          '■ 活動資訊',
          '・時間：{{event_datetime}}',
          '・地點：{{event_location}}',
          '{{#participant_list_url}}・參加者名單：{{participant_list_url}}{{/participant_list_url}}',
          '',
          '{{#event_manage_url}}活動管理：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.settlement.eligible': {
    label: 'H10 結算可能',
    description: '結算可能通知',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '【重要】結算可能になりました｜{{event_name}}（結算ID {{settlement_id}}）',
        body: [
          '{{organizer_name}} 様',
          '',
          '{{event_name}} の結算が可能になりました。',
          '',
          '■ 結算情報',
          '・結算ID：{{settlement_id}}',
          '{{#settlement_period}}・結算対象期間：[ {{settlement_period}} ]{{/settlement_period}}',
          '・主催者受取金額：{{settlement_amount}}',
          '・結算可能日：{{settlement_available_at}}',
          '',
          '{{#payout_detail_url}}明細確認：{{payout_detail_url}}{{/payout_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '【重要】已可結算｜{{event_name}}（結算ID {{settlement_id}}）',
        body: [
          '{{organizer_name}} 您好',
          '',
          '「{{event_name}}」已達可結算狀態。',
          '',
          '■ 結算資訊',
          '・結算ID：{{settlement_id}}',
          '{{#settlement_period}}・結算期間：[ {{settlement_period}} ]{{/settlement_period}}',
          '・主辦可領金額：{{settlement_amount}}',
          '・可結算日期：{{settlement_available_at}}',
          '',
          '{{#payout_detail_url}}查看明細：{{payout_detail_url}}{{/payout_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.payout.succeeded': {
    label: 'H11 送金完了',
    description: '送金完了通知',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '送金完了｜結算金を振り込みました（結算ID {{settlement_id}}）',
        body: [
          '{{organizer_name}} 様',
          '',
          '結算金の送金が完了しました。',
          '',
          '■ 送金情報',
          '・結算ID：{{settlement_id}}',
          '・送金金額：{{payout_amount}}',
          '・送金日時：{{payout_at}}',
          '・ステータス：{{payout_status}}',
          '',
          '{{#payout_detail_url}}明細：{{payout_detail_url}}{{/payout_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '打款完成｜結算金已匯出（結算ID {{settlement_id}}）',
        body: [
          '{{organizer_name}} 您好',
          '',
          '結算金已完成打款。',
          '',
          '■ 打款資訊',
          '・結算ID：{{settlement_id}}',
          '・打款金額：{{payout_amount}}',
          '・打款時間：{{payout_at}}',
          '・狀態：{{payout_status}}',
          '',
          '{{#payout_detail_url}}明細：{{payout_detail_url}}{{/payout_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.payout.failed': {
    label: 'H12 送金保留/失敗',
    description: '送金保留/失敗通知',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '【要対応】送金が保留/失敗しました（結算ID {{settlement_id}}）',
        body: [
          '{{organizer_name}} 様',
          '',
          '結算金の送金が保留または失敗しました。対応が必要です。',
          '',
          '■ 状況',
          '・結算ID：{{settlement_id}}',
          '・ステータス：{{payout_status}}',
          '{{#payout_hold_reason}}・理由：{{payout_hold_reason}}{{/payout_hold_reason}}',
          '',
          '{{#required_action_text}}■ 対応方法',
          '{{required_action_text}}',
          '{{/required_action_text}}',
          '{{#action_url}}対応リンク：{{action_url}}{{/action_url}}',
          '{{#bank_update_url}}口座情報の更新：{{bank_update_url}}{{/bank_update_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '【需處理】打款保留/失敗（結算ID {{settlement_id}}）',
        body: [
          '{{organizer_name}} 您好',
          '',
          '結算金打款目前處於保留或失敗狀態，需要您處理。',
          '',
          '■ 狀態',
          '・結算ID：{{settlement_id}}',
          '・狀態：{{payout_status}}',
          '{{#payout_hold_reason}}・原因：{{payout_hold_reason}}{{/payout_hold_reason}}',
          '',
          '{{#required_action_text}}■ 需要你處理的事項',
          '{{required_action_text}}',
          '{{/required_action_text}}',
          '{{#action_url}}前往處理：{{action_url}}{{/action_url}}',
          '{{#bank_update_url}}更新收款帳戶：{{bank_update_url}}{{/bank_update_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.refund.occurred': {
    label: 'H13 返金発生',
    description: '返金発生通知',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '返金が発生しました｜{{event_name}}（注文 {{order_id}}）',
        body: [
          '{{organizer_name}} 様',
          '',
          '返金が発生しました。売上/結算金額に影響する場合があります。',
          '',
          '■ 返金情報',
          '・注文番号：{{order_id}}',
          '{{#participant_display_name}}・参加者：{{participant_display_name}}{{/participant_display_name}}',
          '・返金金額：{{refund_amount}}',
          '・返金日時：{{refunded_at}}',
          '{{#refund_reason}}・理由：{{refund_reason}}{{/refund_reason}}',
          '',
          '{{#refund_detail_url}}詳細：{{refund_detail_url}}{{/refund_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '已發生退款｜{{event_name}}（訂單 {{order_id}}）',
        body: [
          '{{organizer_name}} 您好',
          '',
          '系統已產生退款，可能會影響您的收入/結算金額。',
          '',
          '■ 退款資訊',
          '・訂單編號：{{order_id}}',
          '{{#participant_display_name}}・參加者：{{participant_display_name}}{{/participant_display_name}}',
          '・退款金額：{{refund_amount}}',
          '・退款時間：{{refunded_at}}',
          '{{#refund_reason}}・原因：{{refund_reason}}{{/refund_reason}}',
          '',
          '{{#refund_detail_url}}詳情：{{refund_detail_url}}{{/refund_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.dispute.updated': {
    label: 'H14 争議/拒付',
    description: '争議/拒付ステータス更新',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '【重要】決済に争議/拒付が発生しました（注文 {{order_id}}）',
        body: [
          '{{organizer_name}} 様',
          '',
          '以下の注文に関して、争議/拒付のステータスが更新されました。',
          '結算の保留や金額調整が発生する可能性があります。',
          '',
          '■ 対象',
          '・注文番号：{{order_id}}',
          '・イベント名：{{event_name}}',
          '・ステータス：{{dispute_status}}',
          '',
          '■ 影響',
          '{{impact_text}}',
          '',
          '{{#required_action_text}}■ 必要な対応',
          '{{required_action_text}}',
          '{{#action_url}}対応リンク：{{action_url}}{{/action_url}}',
          '{{/required_action_text}}',
          '',
          '{{#order_detail_url}}注文詳細：{{order_detail_url}}{{/order_detail_url}}',
          '{{#support_url}}ご不明点：{{support_url}}{{/support_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '【重要】付款發生爭議/拒付（訂單 {{order_id}}）',
        body: [
          '{{organizer_name}} 您好',
          '',
          '以下訂單的爭議/拒付狀態已更新，可能導致結算保留或金額調整。',
          '',
          '■ 對應訂單',
          '・訂單編號：{{order_id}}',
          '・活動：{{event_name}}',
          '・狀態：{{dispute_status}}',
          '',
          '■ 影響',
          '{{impact_text}}',
          '',
          '{{#required_action_text}}■ 需要你處理的事項',
          '{{required_action_text}}',
          '{{#action_url}}處理連結：{{action_url}}{{/action_url}}',
          '{{/required_action_text}}',
          '',
          '{{#order_detail_url}}訂單明細：{{order_detail_url}}{{/order_detail_url}}',
          '{{#support_url}}客服：{{support_url}}{{/support_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.registration.success': {
    label: 'H06 支払完了',
    description: '支払い完了（参加確定）',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '支払い完了｜参加が確定しました：{{event_name}}（{{order_id}}）',
        body: [
          '{{organizer_name}} 様',
          '',
          '参加者の支払いが完了し、参加が確定しました。',
          '',
          '■ 注文情報',
          '・注文番号：{{order_id}}',
          '{{#participant_display_name}}・参加者：{{participant_display_name}}{{/participant_display_name}}',
          '・金額：{{amount}}',
          '{{#fee}}・決済手数料：{{fee}}{{/fee}}',
          '{{#net_amount}}・主催者受取見込み：{{net_amount}}{{/net_amount}}',
          '・支払日時：{{paid_at}}',
          '',
          '{{#order_detail_url}}注文詳細：{{order_detail_url}}{{/order_detail_url}}',
          '{{#event_manage_url}}イベント管理：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '付款成功｜參加已確定：{{event_name}}（{{order_id}}）',
        body: [
          '{{organizer_name}} 您好',
          '',
          '參加者已完成付款，參加資格已確定。',
          '',
          '■ 訂單資訊',
          '・訂單編號：{{order_id}}',
          '{{#participant_display_name}}・參加者：{{participant_display_name}}{{/participant_display_name}}',
          '・金額：{{amount}}',
          '{{#fee}}・平台手續費：{{fee}}{{/fee}}',
          '{{#net_amount}}・主辦預計入帳：{{net_amount}}{{/net_amount}}',
          '・付款時間：{{paid_at}}',
          '',
          '{{#order_detail_url}}訂單明細：{{order_detail_url}}{{/order_detail_url}}',
          '{{#event_manage_url}}活動管理：{{event_manage_url}}{{/event_manage_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.registration.cancel_free': {
    label: 'H05 申込取消（無料）',
    description: '参加者による申込取消（無料）',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '申込が取り消されました｜{{event_name}}（{{order_id}}）',
        body: [
          '{{organizer_name}} 様',
          '',
          '参加者により申込が取り消されました。',
          '',
          '■ 対象',
          '・イベント名：{{event_name}}',
          '・申込番号：{{order_id}}',
          '{{#participant_display_name}}・申込者：{{participant_display_name}}{{/participant_display_name}}',
          '{{#cancelled_at}}・取消日時：{{cancelled_at}}{{/cancelled_at}}',
          '',
          '{{#order_detail_url}}詳細：{{order_detail_url}}{{/order_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '申請已取消｜{{event_name}}（{{order_id}}）',
        body: [
          '{{organizer_name}} 您好',
          '',
          '參加者已取消/撤回報名申請。',
          '',
          '■ 對應資訊',
          '・活動：{{event_name}}',
          '・申請編號：{{order_id}}',
          '{{#participant_display_name}}・申請者：{{participant_display_name}}{{/participant_display_name}}',
          '{{#cancelled_at}}・取消時間：{{cancelled_at}}{{/cancelled_at}}',
          '',
          '{{#order_detail_url}}詳情：{{order_detail_url}}{{/order_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'organizer.registration.cancel_paid': {
    label: 'H05 申込取消（有料）',
    description: '参加者による申込取消（有料）',
    defaultEnabled: false,
    role: 'organizer',
    category: 'transactional',
    line: {},
    email: {
      ja: {
        subject: '申込が取り消されました｜{{event_name}}（{{order_id}}）',
        body: [
          '{{organizer_name}} 様',
          '',
          '参加者により申込が取り消されました。',
          '',
          '■ 対象',
          '・イベント名：{{event_name}}',
          '・申込番号：{{order_id}}',
          '{{#participant_display_name}}・申込者：{{participant_display_name}}{{/participant_display_name}}',
          '{{#cancelled_at}}・取消日時：{{cancelled_at}}{{/cancelled_at}}',
          '',
          '{{#order_detail_url}}詳細：{{order_detail_url}}{{/order_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} サポート：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
      zh: {
        subject: '申請已取消｜{{event_name}}（{{order_id}}）',
        body: [
          '{{organizer_name}} 您好',
          '',
          '參加者已取消/撤回報名申請。',
          '',
          '■ 對應資訊',
          '・活動：{{event_name}}',
          '・申請編號：{{order_id}}',
          '{{#participant_display_name}}・申請者：{{participant_display_name}}{{/participant_display_name}}',
          '{{#cancelled_at}}・取消時間：{{cancelled_at}}{{/cancelled_at}}',
          '',
          '{{#order_detail_url}}詳情：{{order_detail_url}}{{/order_detail_url}}',
          '',
          '――――――――――',
          '',
          '{{service_name}} 客服：{{support_url}}',
          '',
          '――――――――――',
        ].join('\n'),
      },
    },
  },
  'user.community.event_published': {
    role: 'user',
    category: 'marketing',
    line: {
      ja: {
        title: '{{communityName}} の新しいイベント',
        body: '{{eventTitle}} が公開されました。',
      },
    },
    email: {
      ja: {
        subject: '{{communityName}} の新しいイベントが公開されました',
        body: '{{eventTitle}} が公開されました。詳細はこちら: {{url}}',
      },
    },
  },
  'user.registration.success': {
    role: 'user',
    category: 'transactional',
    line: {
      ja: {
        title: '申込が完了しました',
        body: '{{eventTitle}}\n{{eventDate}} {{eventTime}}\n{{location}}',
      },
    },
    email: {
      ja: {
        subject: '申込が完了しました',
        body: '{{eventTitle}}\n{{eventDate}} {{eventTime}}\n{{location}}',
      },
    },
  },
  'user.cancel.success': {
    role: 'user',
    category: 'transactional',
    line: {
      ja: {
        title: 'キャンセルが完了しました',
        body: '{{eventTitle}} の申込をキャンセルしました。',
      },
    },
    email: {
      ja: {
        subject: 'キャンセルが完了しました',
        body: '{{eventTitle}} の申込をキャンセルしました。',
      },
    },
  },
  'user.event.reminder': {
    role: 'user',
    category: 'transactional',
    line: {
      ja: {
        title: '明日イベントがあります',
        body: '{{eventTitle}}\n{{eventDate}} {{eventTime}}\n{{location}}',
      },
    },
    email: {
      ja: {
        subject: '明日イベントがあります',
        body: '{{eventTitle}}\n{{eventDate}} {{eventTime}}\n{{location}}',
      },
    },
  },
  'admin.system.alert': {
    role: 'admin',
    category: 'operational',
    line: {
      ja: {
        title: 'システムアラート',
        body: '{{message}}',
      },
    },
    email: {
      ja: {
        subject: 'システムアラート',
        body: '{{message}}',
      },
    },
  },
  'admin.business.alert': {
    role: 'admin',
    category: 'operational',
    line: {
      ja: {
        title: 'ビジネスアラート',
        body: '{{message}}',
      },
    },
    email: {
      ja: {
        subject: 'ビジネスアラート',
        body: '{{message}}',
      },
    },
  },
  'admin.notification.alert': {
    role: 'admin',
    category: 'operational',
    line: {
      ja: {
        title: '通知システムアラート',
        body: '{{message}}',
      },
    },
    email: {
      ja: {
        subject: '通知システムアラート',
        body: '{{message}}',
      },
    },
  },
};
