export const MOBILE_EVENT_REGISTRATION_DRAFT_KEY = 'MOBILE_EVENT_REGISTRATION_DRAFT';
export const MOBILE_EVENT_PENDING_PAYMENT_KEY = 'MOBILE_EVENT_PENDING_PAYMENT';
export const MOBILE_EVENT_SUCCESS_KEY = 'MOBILE_EVENT_SUCCESS';
export const MOBILE_CLASS_SUCCESS_KEY = 'MOBILE_CLASS_SUCCESS';
